version: '3.7'

services:
  app:
    build: .
    container_name: tdd-products-api
    entrypoint: ./.docker/entrypoint.sh
    env_file:
      - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/home/node/app
    depends_on:
      - mysql
    networks:
      - internal-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    tty: true
    volumes:
      - mysql:/var/lib/mysql 
    environment:
      - MYSQL_DATABASE=${TYPEORM_DATABASE}
      - MYSQL_USER=${TYPEORM_USERNAME}
      - MYSQL_PASSWORD=${TYPEORM_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${TYPEORM_PASSWORD}

    networks:
      - internal-network


volumes:
  mysql:

networks:
  internal-network:
    driver: bridge




